# Generated by Django 5.2.8 on 2025-11-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
