# Generated by Django 6.0 on 2025-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
