# Generated by Django 5.2.8 on 2025-11-24 11:04

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expiry', '0002_delete_choice_delete_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('entry_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('item_category', models.CharField(choices=[('FRUIT', 'Fruit'), ('DAIRY', 'Dairy'), ('BREAD', 'Bread'), ('VEG', 'Vegetables'), ('EGGS', 'Eggs'), ('MEAT', 'Meat')], max_length=5)),
                ('storage_type', models.CharField(choices=[('FRDG', 'Fridge'), ('FRZR', 'Freezer'), ('AMBI', 'Ambient')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
