# Generated by Django 5.2.8 on 2025-12-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0005_notifjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='notification_day',
            new_name='notification_days',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='notification_enabled',
            new_name='notifications',
        ),
    ]
