# Generated by Django 6.0 on 2025-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0006_rename_notification_day_usersettings_notification_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notification_days',
            field=models.JSONField(default=list),
        ),
    ]
