# Generated by Django 6.0 on 2025-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0008_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notification_time',
            field=models.TimeField(null=True),
        ),
    ]
