# Generated by Django 6.0 on 2025-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0009_alter_usersettings_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notification_days',
            field=models.JSONField(default=list, null=True),
        ),
    ]
