# Generated by Django 6.0 on 2025-12-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0010_alter_usersettings_notification_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
