# Generated by Django 6.0 on 2025-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry', '0011_item_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deletion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
